### ISSUE TITLE
Getting errors on startup

### ISSUE THREAD

**Issue by Bios-Marcel** [thecodeah/space-typer#3]
```
[marcel@macel space-typer]$ ./space-typer 
Traceback (most recent call last):
  File "space-typer.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/codeah/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "arcade/__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/codeah/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "arcade/application.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/codeah/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "arcade/window_commands.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/codeah/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "pyglet/gl/__init__.py", line 239, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/codeah/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "pyglet/window/__init__.py", line 1896, in <module>
  File "pyglet/gl/__init__.py", line 208, in _create_shadow_window
  File "pyglet/window/xlib/__init__.py", line 166, in __init__
  File "pyglet/window/__init__.py", line 571, in __init__
  File "pyglet/window/xlib/__init__.py", line 263, in _create
  File "pyglet/gl/xlib.py", line 323, in attach
  File "pyglet/gl/xlib.py", line 328, in set_current
  File "pyglet/gl/base.py", line 301, in set_current
  File "pyglet/gl/gl_info.py", line 98, in set_active_context
  File "pyglet/gl/gl_info.py", line 170, in have_version
  File "pyglet/gl/gl_info.py", line 170, in <listcomp>
ValueError: invalid literal for int() with base 10: ''
[3287] Failed to execute script space-typer
[marcel@macel space-typer]$ 
```

## How to reproduce

1. Download zip
2. Unpack
3. run `space-typer`

**Comment by thecodeah** [comment]
That's odd. The logs seems to have my directories in them.

So far I can't think of a reason why this'd happen. This might be a PyInstaller issue (The tool I used to bundle the application)

**Comment by Bios-Marcel** [comment]
Doubt that the issue lies in the tooling, it's most likely a bad configuration.

**Comment by thecodeah** [comment]
The reason I suspect it's the tool is because it's currently broken and I had to do a little workaround to get it to work.

I have tried different configurations and have uploaded it to the v1.0.0 release. Hope it works now.

**Comment by Bios-Marcel** [comment]
Internet sucks rn, will try when I am home (tomorrow).

**Comment by thecodeah** [comment]
Seems to work fine for others now, closing this issue.
